branch-defaults:
  master:
    environment: null
global:
  application_name: spurt
  default_ec2_keyname: null
  default_platform: Docker 1.3.3
  default_region: us-west-1
  profile: eb-cli
  sc: git
