branch-defaults:
  master:
    environment: spurtfirst
global:
  application_name: spurtapp
  default_ec2_keyname: pear
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-west-1
  profile: eb-cli
  sc: git
