branch-defaults:
  master:
    environment: spurted2
global:
  application_name: spurt
  default_ec2_keyname: aws-eb
  default_platform: Python
  default_region: us-west-1
  profile: eb-cli
  sc: git
