branch-defaults:
  master:
    environment: null
global:
  application_name: spurt
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-west-1
  profile: eb-cli
  sc: git
