branch-defaults:
  default:
    environment: spikebackend
  master:
    environment: spikebackend
global:
  application_name: spikebackend
  default_ec2_keyname: pear
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
