branch-defaults:
  default:
    environment: gauss
  master:
    environment: gauss
global:
  application_name: gauss
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
